### ISSUE TITLE
can't build or build:watch it

### ISSUE THREAD

**Issue by dkipp** [nyctef/electron-from-scratch#7]
great articles!
looking forward to part 4

I tried to build it. in its current state it doesn't work. the console output is long... Does it work for you?

**Comment by nyctef** [comment]
I'm not seeing the same problem - doing `npm install` and then `npm run build` seems to work fine :/ Can you post more details about the error?

**Comment by dkipp** [comment]
here are the details:

1. git clone https://github.com/nyctef/electron-from-scratch
2. npm install (inside electron-from-scratch folder)

`PS C:\Users\dck\Documents> git clone https://github.com/nyctef/electron-from-scratch
Cloning into 'electron-from-scratch'...
remote: Enumerating objects: 315, done.
Receiving objects:  97% (306/315)   0 (delta 0), pack-reused 315Receiving objects:  90% (284/315)
Receiving objects: 100% (315/315), 143.05 KiB | 597.00 KiB/s, done.
Resolving deltas: 100% (133/133), done.
PS C:\Users\dck\Documents> cd .\electron-from-scratch\
PS C:\Users\dck\Documents\electron-from-scratch> npm install

> node-sass@4.11.0 install C:\Users\dck\Documents\electron-from-scratch\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> electron@4.0.4 postinstall C:\Users\dck\Documents\electron-from-scratch\node_modules\electron
> node install.js

Downloading tmp-10756-1-SHASUMS256.txt-4.0.4
[============================================>] 100.0% of 4.74 kB (4.74 kB/s)

> node-sass@4.11.0 postinstall C:\Users\dck\Documents\electron-from-scratch\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\dck\Documents\electron-from-scratch\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.3.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:149:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:149:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError ' +
gyp verb `which` failed     '(C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F ' +
gyp verb `which` failed     '(C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E ' +
gyp verb `which` failed     '(C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:149:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:149:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\dck\Documents\electron-from-scratch\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:149:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError ' +
gyp verb `which` failed     '(C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F ' +
gyp verb `which` failed     '(C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E ' +
gyp verb `which` failed     '(C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at ' +
gyp verb `which` failed     'C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:149:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\dck\Documents\electron-from-scratch\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\dck\Documents\electron-from-scratch\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\dck\Documents\electron-from-scratch\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:149:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dck\\Documents\\electron-from-scratch\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\dck\Documents\electron-from-scratch\node_modules\node-sass
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dck\AppData\Roaming\npm-cache\_logs\2019-09-17T07_19_56_458Z-debug.log
PS C:\Users\dck\Documents\electron-from-scratch>`
